[tool.semantic_release]
version_variable = "setup.py:__version__"   # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
dist_path = "./"                            # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default

[tool.semantic_release.changelog]
exclude_commit_patterns     =  [ "Merge pull", "ci:"]